version: 3
workdir: internal
allow:
  deepScan: true

components:
  domain: { in: domain }
  usecase: { in: usecases }
  adapter: { in: adapters/** }
  infra: { in: frameworks }

commonComponents:
  - domain

deps:
  usecase:
    mayDependOn:
      - domain
  adapter:
    mayDependOn:
      - usecase
  infra:
    mayDependOn:
      - adapter
